collector:
  image: sre-bot-collector
  tag: latest
  replicas: 1
  scrapeTarget: http://prometheus:9090/metrics
  listenPort: 8080
  appName: sre-bot-collector

aggregator:
  image: sre-bot-aggregator
  tag: latest
  replicas: 1
  appName: sre-bot-aggregator

detector:
  image: sre-bot-detector
  tag: latest
  replicas: 1
  appName: sre-bot-detector

agent:
  image: sre-bot-agent
  tag: latest
  replicas: 1
  ollamaHost: http://ollama.sre-bot-infra.svc.cluster.local:11434
  ollamaModel: llama3.2:3b
  appName: sre-bot-agent

kafka:
  broker: kafka.sre-bot-infra.svc.cluster.local:9092
  topic: metrics

clickhouse:
  host: clickhouse.sre-bot-infra.svc.cluster.local

ns:
  infra_namespace: sre-bot-infra
  app_namespace: sre-bot-apps
  app: sre-bot

zookeeper:
  name: zookeeper
  image: confluentinc/cp-zookeeper
  tag: "7.4.0"
  client_port: 2181
  container_port: 2181