apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ .Values.zookeeper.name }}
    namespace: {{ .Values.ns.infra_namespace }}
spec:
    serviceName: {{ .Values.zookeeper.name }}
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.zookeeper.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.zookeeper.name }}
        spec:
            containers:
                - name: {{ .Values.zookeeper.name }}
                  image: {{ .Values.zookeeper.image }}:{{ .Values.zookeeper.tag }}
                  env:
                    - name: ZOOKEEPER_CLIENT_PORT
                      value: "{{ .Values.zookeeper.client_port }}"
                  ports:
                    - containerPort: {{ .Values.zookeeper.container_port }}