apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.zookeeper.name }}
    namespace: {{ .Values.ns.infra_namespace }}
spec:
    clusterIP: None
    selector:
        app: {{ .Values.zookeeper.name }}
    ports:
        - port: {{ .Values.zookeeper.client_port }}
          targetPort: {{ .Values.zookeeper.container_port }}