apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.collector.appName }}
spec:
  replicas: {{ .Values.collector.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.collector.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.collector.appName }}
    spec:
      containers:
      - name: collector
        image: {{ .Values.collector.image }}:{{ .Values.collector.tag }}
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: sre-bot-config
        livenessProbe:
            httpGet:
                path: /health
                port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
        readinessProbe:
            httpGet:
                path: /health
                port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
        resources:
            requests:
                memory: "64Mi"
                cpu: "250m"
            limits:
                memory: "128Mi"
                cpu: "500m"
