apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ns.app }}-config
  namespace: {{ .Values.ns.app_namespace }}
data:
  SCRAPE_TARGET: "{{ .Values.collector.scrapeTarget }}"
  LISTEN_PORT: "{{ .Values.collector.listenPort }}"
  KAFKA_BROKER: "{{ .Values.kafka.broker }}"
  KAFKA_TOPIC: "{{ .Values.kafka.topic }}"
  CLICKHOUSE_HOST: "{{ .Values.clickhouse.host }}"
  LLM_BACKEND: "{{ .Values.agent.ollamaHost }}"
  LLM_MODEL: "{{ .Values.agent.ollamaModel }}"