apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.detector.appName }}
spec:
  replicas: {{ .Values.detector.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.detector.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.detector.appName }}
    spec:
      containers:
      - name: agent
        image: {{ .Values.detector.image }}:{{ .Values.detector.tag }}
        envFrom:
          - configMapRef:
              name: sre-bot-config
        livenessProbe:
            exec:
                command:
                    - python3
                    - -c
                    - "import os; os.getpid()"
            initialDelaySeconds: 10
            periodSeconds: 30
        readinessProbe:
            exec:
                command:
                    - python3
                    - -c
                    - "import os; os.getpid()"
            initialDelaySeconds: 5
            periodSeconds: 30
        resources:
            requests:
                memory: "128Mi"
                cpu: "250m"
            limits:
                memory: "256Mi"
                cpu: "500m"
