apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.collector.appName }}
    namespace: {{ .Values.ns.app_namespace }}
spec:
    selector:
        app: {{ .Values.collector.appName }}
    ports:
        - name: container
          port: {{ .Values.collector.listenPort }}
          targetPort: {{ .Values.collector.listenPort }}