apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.prometheus.name }}
    namespace: {{ .Values.ns.monitoring_namespace }}
spec:
    selector:
        app: {{ .Values.prometheus.name }}
    ports:
        - name: container
          port: {{ .Values.prometheus.listenPort }}
          targetPort: {{ .Values.prometheus.listenPort }}