apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.name }}-configmap
  namespace: {{ .Values.ns.monitoring_namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name : 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
      - job_name: 'sre-bot-apps'
        static_configs:
          - targets: ['sre-bot-collector.sre-bot-apps.svc.cluster.local:8080']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.sre-bot-monitoring.svc.cluster.local:9100']